### ISSUE TITLE
async not working

### ISSUE THREAD

**Issue by Brupes** [calle-gunnarsson/fivem-postgres-async#2]
for some reason the async part is not working
atrached is the returned log of the error. i hope you can solve it even after 2 years...
basically i am trying to convert a mysql server to postgres because i want to use the postgres database and i got stuck in this error... the sync part seems to work because it is not returning any error
best regards
bruno

![image](https://user-images.githubusercontent.com/25111697/83975726-2df57d00-a8ed-11ea-9d85-6a9f4afc2e3d.png)

**Comment by theCarlG** [comment]
This project is sort of abandone, I had a rewritten version i Javascript but that code is long gone.. Sorry

**Comment by Brupes** [comment]
no problem. i solved my async problem with some cheating... :)
Basically i created a thread to execute the normal sync so it can execute the querys in a asynchronous mode.
